/**
 * 神煞手写加厚 · 扫尾批（原 atlas 骨架剩余）
 * 合并进 SHENSHA_RICH；排盘算法不在此改。
 */
import type { CodexDossier } from './codex-encyclopedia-types.ts';
import { featuredShenshaRich } from './codex-shensha-schema.ts';
import {
  aliasEntryLookupLines,
  changShengStageLookupLines,
  feiRenLookupLines,
  fuXingAliasLookupLines,
  geJiaoLookupLines,
  guChenLookupLines,
  guaSuLookupLines,
  jinShenLookupLines,
  jiaoShaLookupLines,
  liuELookupLines,
  maTouDaiJianLookupLines,
  piMaLookupLines,
  tianLuoDiWangLookupLines,
  tongZiLookupLines,
  tuiShenLookupLines,
  xunKongLookupLines,
  yuanChenLookupLines,
  ziWeiLookupLines,
} from './shensha-calc-extra.ts';

function rich(cfg: Parameters<typeof featuredShenshaRich>[0]): Partial<CodexDossier> {
  return featuredShenshaRich(cfg);
}

/** 扫尾 32 条 */
export const SHENSHA_RICH_REST: Record<string, Partial<CodexDossier>> = {
  'ss:正印': rich({
    name: '正印',
    whatIs:
      '正印是什么：十神正印的图鉴入口。像有人托底、可学可被养——学习与贵人感；对照十神原局，不是单独神煞判决。',
    lookupLabel: '图鉴入口 · 对照十神正印',
    lookupLines: aliasEntryLookupLines('正印', '排盘以十神「正印」落柱为准；本条解印象与边界'),
    lookupPeer: '十神→正印',
    likes: ['学习托底', '合印星原局', '被滋养也自立'],
    dislikes: ['当作必贵人', '依赖不成长', '脱离日主'],
    strength: '托底、学习、被认可感。',
    career: '利文职、培训、背书岗；要交付。',
    wealth: '稳定供养感；忌只吃老本。',
    love: '照顾型缘分；分清滋养与依赖。',
    body: '睡眠与脾胃；过思伤。',
    chartExtra: '正印是十神对照入口，须回原局。',
    positive: '正面：有托可学。失衡：依赖或空印。',
    memory: '正印入口 = 托底学习。辅助，勿单独断。',
    coreKeyword: '正印 · 托底学习',
    pillarMeaning: {
      year: '年柱见正印气：早年/家族滋养或学业氛围。',
      month: '月柱见正印气：事业场背书与学习窗口。',
      day: '日柱见正印气：本人托底感；要自立。',
      hour: '时柱见正印气：晚成偏学养成果。',
    },
  }),
  'ss:飞刃': rich({
    name: '飞刃',
    whatIs:
      '飞刃是什么：羊刃的对冲位。像刀锋飞出去——刚锐冲突提醒；宜防护降温，不作恐吓「必血光」。',
    lookupLabel: '日干羊刃之冲支',
    lookupLines: feiRenLookupLines(),
    lookupPeer: '日干→飞刃',
    likes: ['防护与冷静', '合羊刃/血刃看', '冲突先降温'],
    dislikes: ['恐吓式血光断语', '硬刚冲突', '漠视安全'],
    strength: '提醒锋利关口、促使防护。',
    career: '高压对抗宜流程护具。',
    wealth: '撕破脸谈判前留缓冲。',
    love: '伤人话要收；先停火。',
    body: '锐器/运动防护；交通留心。',
    chartExtra: '飞刃标「刚锐提醒」，不是灾难判决。',
    positive: '正面：促使防护。失衡：恐吓或硬冲。',
    memory: '飞刃 = 羊刃冲：锋利宜护。辅助，勿单独断。',
    coreKeyword: '飞刃 · 刚锐防护',
    pillarMeaning: {
      year: '年柱见飞刃：早年尖锐/防护议题。',
      month: '月柱见飞刃：事业冲突关口宜冷静。',
      day: '日柱见飞刃：本人锋利感；练收口。',
      hour: '时柱见飞刃：出口期留心防护。',
    },
  }),
  'ss:紫微': rich({
    name: '紫微',
    whatIs:
      '紫微是什么：尊贵、中枢感的神煞入口（命理口径，非紫微斗数整套）。本产品简化：日支帝旺时标——像站到舞台中央；要德配位。',
    lookupLabel: '日支帝旺（简化入口）',
    lookupLines: ziWeiLookupLines(),
    lookupPeer: '日干→帝旺/紫微',
    likes: ['合将星/国印看', '名位配交付', '中枢要授权'],
    dislikes: ['当作必大贵', '空居中无货', '脱离原局'],
    strength: '中枢感、可见度、被期待扛事。',
    career: '利核心岗；学会授权。',
    wealth: '名可变现；忌虚名耗财。',
    love: '场合感强；留平等。',
    body: '公开压力伤睡；规律作息。',
    chartExtra: '紫微是简化入口，不是斗数整盘。',
    positive: '正面：有中枢感。失衡：虚位或过压。',
    memory: '紫微简化 = 帝旺中枢。辅助，勿单独断。',
    coreKeyword: '紫微 · 中枢尊贵',
    pillarMeaning: {
      year: '年柱议题见紫微对照：早年被期待中枢感。',
      month: '月柱议题见紫微对照：事业核心窗口。',
      day: '日柱见紫微：本人中枢感；要交付。',
      hour: '时柱议题见紫微对照：晚成偏核心成果。',
    },
  }),
  'ss:进神': rich({
    name: '进神',
    whatIs:
      '进神是什么：进取、向前推进的日柱象。特定日柱——像绿灯可加一脚；要落地，不是必升迁。',
    lookupLabel: '日柱进神日',
    lookupLines: jinShenLookupLines(),
    lookupPeer: '日柱→进神',
    likes: ['小步推进', '合退神对照', '写清里程碑'],
    dislikes: ['当作必成', '盲目加码', '无复盘猛冲'],
    strength: '推进窗口、进取气。',
    career: '利立项推进；设检查点。',
    wealth: '宜进取投资有上限。',
    love: '关系可往前走一步；说清。',
    body: '兴奋易熬夜；守睡眠。',
    chartExtra: '进神以日柱论；标推进窗口。',
    positive: '正面：能推进。失衡：空冲无岸。',
    memory: '进神 = 特定日柱：可进要落。辅助，勿单独断。',
    coreKeyword: '进神 · 进取推进',
    pillarMeaning: {
      year: '（进神以日柱论）年柱不单独成进神。',
      month: '（进神以日柱论）月柱不单独成进神；事业可借推进气。',
      day: '日柱命中进神：本人处推进窗口；要里程碑。',
      hour: '（进神以日柱论）时柱不单独成进神。',
    },
  }),
  'ss:退神': rich({
    name: '退神',
    whatIs:
      '退神是什么：收缩、宜守的日柱象。特定日柱——像该减负收摊；不是永久退场，是节奏。',
    lookupLabel: '日柱退神日',
    lookupLines: tuiShenLookupLines(),
    lookupPeer: '日柱→退神',
    likes: ['减负复盘', '合进神对照', '守住基本盘'],
    dislikes: ['当作必败', '恐慌清仓', '该守却硬冲'],
    strength: '收缩窗口、促使复盘。',
    career: '利收尾清库存；忌新开多线。',
    wealth: '宜守不宜梭哈。',
    love: '需要空间时说清；别冷战。',
    body: '疲劳期先恢复。',
    chartExtra: '退神以日柱论；标宜守节奏。',
    positive: '正面：能收能守。失衡：恐慌或死守。',
    memory: '退神 = 特定日柱：宜守复盘。辅助，勿单独断。',
    coreKeyword: '退神 · 收缩宜守',
    pillarMeaning: {
      year: '（退神以日柱论）年柱不单独成退神。',
      month: '（退神以日柱论）月柱不单独成退神；事业宜减负。',
      day: '日柱命中退神：本人处收缩窗口；先复盘。',
      hour: '（退神以日柱论）时柱不单独成退神。',
    },
  }),
  'ss:富星': rich({
    name: '富星',
    whatIs:
      '富星是什么：富裕、资源丰厚感的对照。本产品与仓廪同落——像库里有货；要出入流通，不是堆满即富。',
    lookupLabel: '与仓廪同（日干之库）',
    lookupLines: fuXingAliasLookupLines(),
    lookupPeer: '日干→富星/仓廪',
    likes: ['入库清淤', '合禄神看', '流通变现'],
    dislikes: ['当作必暴富', '只存不出', '恐吓破耗'],
    strength: '资源托底、丰厚感。',
    career: '利资源运营；定期出库。',
    wealth: '宜储蓄与盘点；忌死守。',
    love: '用实质照顾；别只存情绪。',
    body: '脾胃作息；规律。',
    chartExtra: '富星≈仓廪对照；要流通。',
    positive: '正面：有库可托。失衡：库满不疏。',
    memory: '富星 ≈ 仓廪：蓄要流通。辅助，勿单独断。',
    coreKeyword: '富星 · 资源丰厚',
    pillarMeaning: {
      year: '年柱见富星：早年/家族资源议题。',
      month: '月柱见富星：事业资源窗口。',
      day: '日柱见富星：本人库藏感；要清淤。',
      hour: '时柱见富星：出口期宜沉淀入库。',
    },
  }),
  'ss:马头带剑': rich({
    name: '马头带剑',
    whatIs:
      '马头带剑是什么：奔波中带锋芒的复合提醒。驿马遇上羊刃/血刃/飞刃——像赶路还握刀；要护具与边界。',
    lookupLabel: '驿马 + 刃类同见',
    lookupLines: maTouDaiJianLookupLines(),
    lookupPeer: '驿马×刃→马头带剑',
    likes: ['动中防护', '合驿马/羊刃看', '行程留缓冲'],
    dislikes: ['恐吓式必出事', '为动而刚', '无护具硬闯'],
    strength: '提醒动中风险、促使防护。',
    career: '出差关键局宜备份人与流程。',
    wealth: '奔波费+冲突费双控。',
    love: '异地冲突先降温。',
    body: '劳顿+紧张；恢复与防护。',
    chartExtra: '复合提醒，不是灾难判决。',
    positive: '正面：促使防护。失衡：恐吓或硬刚。',
    memory: '马头带剑 = 马+刃：动要护。辅助，勿单独断。',
    coreKeyword: '马头带剑 · 动中锋芒',
    pillarMeaning: {
      year: '年柱见马头带剑：早年迁动带锋芒议题。',
      month: '月柱见马头带剑：事业调动冲突关口。',
      day: '日柱见马头带剑：本人动中易刚；练收。',
      hour: '时柱见马头带剑：出口期行程留护。',
    },
  }),
  'ss:华盖（驿）': rich({
    name: '华盖（驿）',
    whatIs:
      '华盖（驿）是什么：华盖与驿马同见时的漂泊艺文感。像带着信仰在路上——宜动中求静；不是必孤独终老。',
    lookupLabel: '华盖 + 驿马同见',
    lookupLines: aliasEntryLookupLines(
      '华盖（驿）',
      '排盘：华盖与驿马同柱或同盘对照时标此入口',
    ),
    lookupPeer: '华盖×驿马',
    likes: ['动中留静室', '合华盖/驿马看', '艺文可上路'],
    dislikes: ['当作必孤漂', '无归岸瞎跑', '拒绝一切连结'],
    strength: '漂泊中的精神深度提醒。',
    career: '利巡回创作/顾问；要归岸。',
    wealth: '差旅预算；忌漂无账。',
    love: '要自由度也要约定。',
    body: '劳顿+思虑；独处恢复。',
    chartExtra: '对照入口；分清滋养独处与拒绝。',
    positive: '正面：动中有深度。失衡：孤漂无岸。',
    memory: '华盖（驿）= 艺文在路上。辅助，勿单独断。',
    coreKeyword: '华盖驿 · 动中求静',
    pillarMeaning: {
      year: '年柱见华盖（驿）：早年漂泊艺文底色。',
      month: '月柱见华盖（驿）：事业巡回窗口。',
      day: '日柱见华盖（驿）：本人动中清高感；留门。',
      hour: '时柱见华盖（驿）：晚成偏巡回成果。',
    },
  }),
  'ss:动态': rich({
    name: '动态',
    whatIs:
      '动态是什么：动象总览入口。见驿马或冲合则动——像天气起风；宜有归岸，不是必升迁远行。',
    lookupLabel: '驿马等动象对照',
    lookupLines: aliasEntryLookupLines(
      '动态',
      '本产品：见驿马时标动态；亦提示冲合动象合看',
    ),
    lookupPeer: '驿马→动态',
    likes: ['有目标的动', '合驿马/天马看', '动后复盘'],
    dislikes: ['为动而动', '无归岸', '当作必好事'],
    strength: '提醒变动窗口。',
    career: '利项目制出差；写期限。',
    wealth: '动中有费；留缓冲。',
    love: '说清见面节奏。',
    body: '劳顿伤睡；恢复。',
    chartExtra: '总览入口，不是单独星。',
    positive: '正面：能机动。失衡：漂无岸。',
    memory: '动态 = 动象总览：要归岸。辅助，勿单独断。',
    coreKeyword: '动态 · 变动总览',
    pillarMeaning: {
      year: '年柱见动态对照：早年迁动底色。',
      month: '月柱见动态对照：事业调动窗口。',
      day: '日柱见动态对照：本人好动；留归岸。',
      hour: '时柱见动态对照：出口期易动。',
    },
  }),
  'ss:孤辰': rich({
    name: '孤辰',
    whatIs:
      '孤辰是什么：早年独立、自立感的提醒。按年支取孤辰支——像习惯自己扛；宜开一扇连结门，不是必孤独。',
    lookupLabel: '年支取孤辰',
    lookupLines: guChenLookupLines(),
    lookupPeer: '年支→孤辰',
    likes: ['合寡宿/华盖看', '深耕也留门', '独当一面'],
    dislikes: ['恐吓式必孤', '拒绝一切靠近', '脱离原局'],
    strength: '自立、独处深度。',
    career: '利研究独担；开协作窗。',
    wealth: '财务自主；忌封闭无账。',
    love: '慢热深交；别活成拒绝。',
    body: '情志与睡眠；找可信出口。',
    chartExtra: '孤辰标自立提醒，不是判决孤独。',
    positive: '正面：能自立。失衡：拒连结。',
    memory: '孤辰 = 年支取：自立留门。辅助，勿单独断。',
    coreKeyword: '孤辰 · 自立提醒',
    pillarMeaning: {
      year: '年柱见孤辰：早年独立底色。',
      month: '月柱见孤辰：事业独当一面。',
      day: '日柱见孤辰：本人自立感；留门。',
      hour: '时柱见孤辰：出口期偏独成。',
    },
  }),
  'ss:寡宿': rich({
    name: '寡宿',
    whatIs:
      '寡宿是什么：清寂、独处的提醒（常论偏晚）。按年支取——像需要静室；不是恐吓「晚景凄凉」。',
    lookupLabel: '年支取寡宿',
    lookupLines: guaSuLookupLines(),
    lookupPeer: '年支→寡宿',
    likes: ['合孤辰看', '静室滋养', '选择性社交'],
    dislikes: ['恐吓式晚景断语', '自我封闭', '脱离原局'],
    strength: '清寂、精神留白。',
    career: '利深耕收尾；保持一扇窗。',
    wealth: '宜简约账户清晰。',
    love: '慢热；质量重于热闹。',
    body: '独处恢复；防闷出病。',
    chartExtra: '寡宿标清寂提醒，慎断晚景。',
    positive: '正面：能静能深。失衡：封闭恐吓。',
    memory: '寡宿 = 年支取：清寂留窗。辅助，勿单独断。',
    coreKeyword: '寡宿 · 清寂提醒',
    pillarMeaning: {
      year: '年柱见寡宿：早年清寂议题。',
      month: '月柱见寡宿：事业场偏静耕。',
      day: '日柱见寡宿：本人需静室；留窗。',
      hour: '时柱见寡宿：出口期宜选择性社交。',
    },
  }),
  'ss:隔角': rich({
    name: '隔角',
    whatIs:
      '隔角是什么：隔阂、难贴合的提醒。按年支取隔角支——像隔着一层膜；宜主动对齐，不作永久疏离判决。',
    lookupLabel: '年支取隔角',
    lookupLines: geJiaoLookupLines(),
    lookupPeer: '年支→隔角',
    likes: ['主动对齐期待', '合孤辰对照', '写清需求'],
    dislikes: ['恐吓式绝交断语', '冷暴力', '脑补被弃'],
    strength: '提醒隔阂点、促使沟通。',
    career: '跨部门先对齐目标。',
    wealth: '合同条款写细。',
    love: '感觉隔时先问清；少脑补。',
    body: '憋闷伤睡；说出口。',
    chartExtra: '隔角标隔阂提醒，宜对齐。',
    positive: '正面：促使沟通。失衡：恐吓或冷战。',
    memory: '隔角 = 年支取：隔着请对齐。辅助，勿单独断。',
    coreKeyword: '隔角 · 隔阂提醒',
    pillarMeaning: {
      year: '年柱见隔角：早年隔阂议题。',
      month: '月柱见隔角：事业协作宜对齐。',
      day: '日柱见隔角：本人易感隔；先问清。',
      hour: '时柱见隔角：出口期沟通写清。',
    },
  }),
  'ss:童子': rich({
    name: '童子',
    whatIs:
      '童子是什么：幼年缘、宗教缘等说法的入口。本产品简化查法——像心里留一块童真/清修位；慎断，勿恐吓「必出家」。',
    lookupLabel: '产品简化日干×支',
    lookupLines: tongZiLookupLines(),
    lookupPeer: '日干→童子',
    likes: ['合华盖看', '清修与好奇', '慎断说法'],
    dislikes: ['恐吓式出家断语', '否定世俗选择', '脱离原局'],
    strength: '清修感、童真好奇。',
    career: '利教育/信仰相关；尊重选择。',
    wealth: '不宜以此断贫富。',
    love: '慢热纯感；勿神话。',
    body: '情志清；勿压抑正常欲。',
    chartExtra: '入口词，慎断宗教/子嗣。',
    positive: '正面：有清修位。失衡：恐吓或否定。',
    memory: '童子 = 简化入口：慎断。辅助，勿单独断。',
    coreKeyword: '童子 · 清修入口',
    pillarMeaning: {
      year: '年柱见童子：早年清修/童真氛围。',
      month: '月柱见童子：事业偏清修场域。',
      day: '日柱见童子：本人清修感；慎断。',
      hour: '时柱见童子：出口期精神兴趣。',
    },
  }),
  'ss:元辰': rich({
    name: '元辰',
    whatIs:
      '元辰是什么：内耗、别扭、不得劲的提醒。年支前后一位——像鞋里进沙；宜清理对焦，勿单断小人。',
    lookupLabel: '年支前后一位',
    lookupLines: yuanChenLookupLines(),
    lookupPeer: '年支→元辰',
    likes: ['清理内耗', '合勾绞对照', '一次只解一事'],
    dislikes: ['恐吓式小人断语', '对外乱战', '压抑不处理'],
    strength: '提醒别扭点、促使清理。',
    career: '流程别扭先改规则。',
    wealth: '糊涂账清一次。',
    love: '别扭先说感受；少猜。',
    body: '紧绷伤睡；放松。',
    chartExtra: '元辰标内耗提醒，不是小人判决。',
    positive: '正面：促使清理。失衡：恐吓或乱战。',
    memory: '元辰 = 年支±1：别扭请清。辅助，勿单独断。',
    coreKeyword: '元辰 · 内耗提醒',
    pillarMeaning: {
      year: '年柱见元辰：早年别扭/内耗议题。',
      month: '月柱见元辰：事业流程易不得劲。',
      day: '日柱见元辰：本人易内耗；先清理。',
      hour: '时柱见元辰：出口前去掉鞋里沙。',
    },
  }),
  'ss:挂剑': rich({
    name: '挂剑',
    whatIs:
      '挂剑是什么：刀剑、意外锋芒的对照入口。本产品与白虎同见时标——像墙上挂着剑；宜防护，不作恐吓。',
    lookupLabel: '白虎同见对照',
    lookupLines: aliasEntryLookupLines(
      '挂剑',
      '本产品：白虎同见时标挂剑；合白虎查法',
    ),
    lookupPeer: '白虎→挂剑',
    likes: ['防护冷静', '合白虎看', '冲突降温'],
    dislikes: ['恐吓式意外断语', '硬刚', '漠视安全'],
    strength: '提醒锋芒关口。',
    career: '高压岗护流程。',
    wealth: '纠纷前留证。',
    love: '言语收刃。',
    body: '锐器交通留心。',
    chartExtra: '对照入口，不是灾难书。',
    positive: '正面：促使防护。失衡：恐吓。',
    memory: '挂剑 ≈ 白虎对照：锋芒宜护。辅助，勿单独断。',
    coreKeyword: '挂剑 · 锋芒防护',
    pillarMeaning: {
      year: '年柱见挂剑：早年锋芒/防护议题。',
      month: '月柱见挂剑：事业高压冲突关口。',
      day: '日柱见挂剑：本人锋利感；收口。',
      hour: '时柱见挂剑：出口期留心防护。',
    },
  }),
  'ss:羊刃（凶读）': rich({
    name: '羊刃（凶读）',
    whatIs:
      '羊刃（凶读）是什么：羊刃过刚时的风险读法入口。同一羊刃可当魄力，也可当过刚——本条专提醒风险侧；合原局喜用。',
    lookupLabel: '羊刃同见 · 凶读入口',
    lookupLines: aliasEntryLookupLines(
      '羊刃（凶读）',
      '查法同羊刃；本条强调过刚、冲突、收口提醒',
    ),
    lookupPeer: '羊刃→凶读',
    likes: ['练收放', '合羊刃正读对照', '喜用同看'],
    dislikes: ['只用凶读恐吓', '否认魄力面', '脱离喜用'],
    strength: '提醒过刚风险。',
    career: '果断后留复核。',
    wealth: '大额勿冲动。',
    love: '强势收一点。',
    body: '怒气伤肝睡；降温。',
    chartExtra: '读法入口，不是第二颗星。',
    positive: '正面：促使收口。失衡：只恐吓。',
    memory: '羊刃凶读 = 过刚提醒。辅助，勿单独断。',
    coreKeyword: '羊刃凶读 · 过刚提醒',
    pillarMeaning: {
      year: '年柱羊刃凶读：早年刚烈风险提醒。',
      month: '月柱羊刃凶读：事业高压宜收。',
      day: '日柱羊刃凶读：本人过刚风险；练收。',
      hour: '时柱羊刃凶读：出口期少冲动拍板。',
    },
  }),
  'ss:天喜红鸾': rich({
    name: '天喜红鸾',
    whatIs:
      '天喜红鸾是什么：喜鸾并见的加强入口。红鸾/天喜同盘时标——喜庆气更显；仍是窗口，不是必婚保票。',
    lookupLabel: '红鸾或天喜同见',
    lookupLines: aliasEntryLookupLines(
      '天喜红鸾',
      '排盘见红鸾或天喜时标复合入口；查法各从本星',
    ),
    lookupPeer: '红鸾×天喜',
    likes: ['合红鸾/天喜看', '庆祝有度', '关系对齐'],
    dislikes: ['当作必婚', '空喜不落地', '恐吓必散'],
    strength: '喜庆加强感。',
    career: '利发布庆典；要实质。',
    wealth: '喜事预算可控。',
    love: '缘动窗口；慢热核实。',
    body: '热闹伤睡；留恢复。',
    chartExtra: '复合入口，不是单独星。',
    positive: '正面：有喜可庆。失衡：空喜或恐吓。',
    memory: '天喜红鸾 = 喜气加强。辅助，勿单独断。',
    coreKeyword: '天喜红鸾 · 喜气加强',
    pillarMeaning: {
      year: '年柱见天喜红鸾对照：早年喜庆氛围。',
      month: '月柱见天喜红鸾对照：事业社交喜窗。',
      day: '日柱见天喜红鸾对照：本人喜缘窗口。',
      hour: '时柱见天喜红鸾对照：出口期庆典感。',
    },
  }),
  'ss:勾绞': rich({
    name: '勾绞',
    whatIs:
      '勾绞是什么：感情/事务纠缠的提醒。年支±3（与绞煞同点）——像勾住放不开；宜拆题，不作道德判决。',
    lookupLabel: '年支前后第三位',
    lookupLines: jiaoShaLookupLines().map((l) => l.replace('绞煞', '勾绞')),
    lookupPeer: '年支→勾绞',
    likes: ['拆题降温', '合绞煞看', '一次一事'],
    dislikes: ['恐吓式纠缠死', '越扯越紧', '道德审判'],
    strength: '提醒纠缠、促使拆解。',
    career: '多方扯皮写权责。',
    wealth: '担保边界写清。',
    love: '先停火再谈一件。',
    body: '紧绷伤肩颈。',
    chartExtra: '与绞煞同点对照；宜拆。',
    positive: '正面：促使拆解。失衡：恐吓缠死。',
    memory: '勾绞 = 年支±3：勾住请拆。辅助，勿单独断。',
    coreKeyword: '勾绞 · 纠缠提醒',
    pillarMeaning: {
      year: '年柱见勾绞：早年纠缠议题。',
      month: '月柱见勾绞：事业扯皮宜写清。',
      day: '日柱见勾绞：本人易感缠；先拆。',
      hour: '时柱见勾绞：出口期少开死结。',
    },
  }),
  'ss:咸池桃花': rich({
    name: '咸池桃花',
    whatIs:
      '咸池桃花是什么：咸池/桃花并称入口。人缘与欲望磁场——分清滋养与消耗；不作出轨判决。',
    lookupLabel: '桃花或咸池同见',
    lookupLines: aliasEntryLookupLines(
      '咸池桃花',
      '查法同桃花/咸池：年日支入三合取桃花支',
    ),
    lookupPeer: '桃花×咸池',
    likes: ['魅力用在正事', '边界诚实', '合桃花看'],
    dislikes: ['恐吓必乱', '魅力当通行证', '背地多线'],
    strength: '吸引与是非双提醒。',
    career: '利对外；忌暧昧耗能。',
    wealth: '人缘可变现；忌乱承诺。',
    love: '有趣要单一清晰。',
    body: '社交过载留独处。',
    chartExtra: '并称入口，不是第二星。',
    positive: '正面：有魅力。失衡：是非消耗。',
    memory: '咸池桃花 = 磁场要边界。辅助，勿单独断。',
    coreKeyword: '咸池桃花 · 磁场边界',
    pillarMeaning: {
      year: '年柱见咸池桃花对照：早年人缘磁场。',
      month: '月柱见咸池桃花对照：事业对外魅力。',
      day: '日柱见咸池桃花对照：本人磁场强；守界。',
      hour: '时柱见咸池桃花对照：出口缘分宜诚实。',
    },
  }),
  'ss:妻妾': rich({
    name: '妻妾',
    whatIs:
      '妻妾是什么：配偶议题说法的图鉴入口。对照十神妻财等——谈关系结构与期待；不作恐吓式婚变判决。',
    lookupLabel: '图鉴入口 · 对照十神妻财',
    lookupLines: aliasEntryLookupLines(
      '妻妾',
      '排盘以十神财星/配偶宫说法为对照；本条解边界',
    ),
    lookupPeer: '十神→妻妾入口',
    likes: ['对齐期待', '合财星原局', '尊重边界'],
    dislikes: ['恐吓式婚变', '物化称呼落地伤人', '脱离十神'],
    strength: '提醒配偶议题要谈清。',
    career: '合作伙伴合同写清。',
    wealth: '共同财务透明。',
    love: '角色期待对齐；少脑补。',
    body: '情绪劳动；休息。',
    chartExtra: '入口词，须回十神原局。',
    positive: '正面：促使谈清。失衡：恐吓物化。',
    memory: '妻妾入口 = 配偶议题对齐。辅助，勿单独断。',
    coreKeyword: '妻妾 · 配偶入口',
    pillarMeaning: {
      year: '年柱议题见妻妾对照：早年家庭角色氛围。',
      month: '月柱议题见妻妾对照：事业伙伴期待。',
      day: '日柱议题见妻妾对照：本人配偶议题；对齐。',
      hour: '时柱议题见妻妾对照：出口期关系节奏。',
    },
  }),
  'ss:夫星': rich({
    name: '夫星',
    whatIs:
      '夫星是什么：伴侣/官星议题的图鉴入口。对照十神官杀——谈承诺与节奏；不作恐吓式必离必合。',
    lookupLabel: '图鉴入口 · 对照十神官杀',
    lookupLines: aliasEntryLookupLines(
      '夫星',
      '排盘以官杀/伴侣说法为对照；本条解边界',
    ),
    lookupPeer: '十神→夫星入口',
    likes: ['承诺节奏对齐', '合官杀原局', '尊重选择'],
    dislikes: ['恐吓式必离合', '性别刻板硬套', '脱离十神'],
    strength: '提醒伴侣/承诺议题。',
    career: '上司/规则场合官杀看。',
    wealth: '共同规划写清。',
    love: '承诺要具体；少神话。',
    body: '压力沟通伤睡。',
    chartExtra: '入口词，须回十神。',
    positive: '正面：促使对齐。失衡：恐吓刻板。',
    memory: '夫星入口 = 伴侣议题对齐。辅助，勿单独断。',
    coreKeyword: '夫星 · 伴侣入口',
    pillarMeaning: {
      year: '年柱议题见夫星对照：早年权威/伴侣氛围。',
      month: '月柱议题见夫星对照：事业规则场。',
      day: '日柱议题见夫星对照：本人伴侣议题；对齐。',
      hour: '时柱议题见夫星对照：出口期承诺节奏。',
    },
  }),
  'ss:披麻': rich({
    name: '披麻',
    whatIs:
      '披麻是什么：孝服、告别场的提醒。年支+3——像需要哀悼的空间；慎断具体丧事，不作恐吓。',
    lookupLabel: '年支顺数第三位',
    lookupLines: piMaLookupLines(),
    lookupPeer: '年支→披麻',
    likes: ['合丧门/吊客看', '留白仪式', '情绪出口'],
    dislikes: ['恐吓式必丧', '压抑哀悼', '脱离原局'],
    strength: '提醒告别窗口、照顾情绪。',
    career: '交接收尾宜仪式。',
    wealth: '大额避开情绪谷底。',
    love: '伤感期陪伴；少硬刚。',
    body: '情志与睡眠。',
    chartExtra: '慎断丧事；标哀感提醒。',
    positive: '正面：促使照顾情绪。失衡：恐吓。',
    memory: '披麻 = 年支+3：告别留白。辅助，勿单独断。',
    coreKeyword: '披麻 · 告别提醒',
    pillarMeaning: {
      year: '年柱见披麻：早年告别/哀感议题。',
      month: '月柱见披麻：事业收尾宜留白。',
      day: '日柱见披麻：本人易感哀；找出口。',
      hour: '时柱见披麻：出口期情绪劳动多。',
    },
  }),
  'ss:六厄': rich({
    name: '六厄',
    whatIs:
      '六厄是什么：关卡、阻滞的提醒。年/日支入三合取厄支——像路上多道坎；宜备份，不是绝路。',
    lookupLabel: '三合取六厄支',
    lookupLines: liuELookupLines(),
    lookupPeer: '年日支→六厄',
    likes: ['Plan B', '合灾煞对照', '小步过坎'],
    dislikes: ['恐吓式必厄', '硬闯无备', '绝望断语'],
    strength: '提醒关卡、促使备份。',
    career: '关键节点留退路。',
    wealth: '大额复核。',
    love: '卡住换说法。',
    body: '压力期体检作息。',
    chartExtra: '六厄标关卡提醒，非绝路。',
    positive: '正面：促使备份。失衡：恐吓硬闯。',
    memory: '六厄 = 三合厄支：过坎备份。辅助，勿单独断。',
    coreKeyword: '六厄 · 关卡提醒',
    pillarMeaning: {
      year: '年柱见六厄：早年关卡议题。',
      month: '月柱见六厄：事业阻滞宜备份。',
      day: '日柱见六厄：本人易感坎；小步。',
      hour: '时柱见六厄：出口前复查路径。',
    },
  }),
  'ss:词馆学堂': rich({
    name: '词馆学堂',
    whatIs:
      '词馆学堂是什么：学堂/词馆同见时的学业对照入口。开智+表达——要练手交稿，不是学历保票。',
    lookupLabel: '学堂或词馆同见',
    lookupLines: aliasEntryLookupLines(
      '词馆学堂',
      '查法各从学堂/词馆日干取支；同见时标复合入口',
    ),
    lookupPeer: '学堂×词馆',
    likes: ['学习+表达', '合文昌看', '交稿练手'],
    dislikes: ['当作必学历', '只学不交', '空谈才华'],
    strength: '学业表达加强感。',
    career: '利考试内容岗；要作品。',
    wealth: '技能可变现。',
    love: '用表达连接。',
    body: '用脑过度伤睡。',
    chartExtra: '复合入口，不是单独星。',
    positive: '正面：能学能写。失衡：空学无交。',
    memory: '词馆学堂 = 学+写要交。辅助，勿单独断。',
    coreKeyword: '词馆学堂 · 学写一体',
    pillarMeaning: {
      year: '年柱见词馆学堂对照：早年文教氛围。',
      month: '月柱见词馆学堂对照：事业进修窗口。',
      day: '日柱见词馆学堂对照：本人学写感；要交稿。',
      hour: '时柱见词馆学堂对照：晚成偏文教成果。',
    },
  }),
  'ss:子孙星': rich({
    name: '子孙星',
    whatIs:
      '子孙星是什么：食伤/子女议题的图鉴入口。对照十神食伤——谈创造与晚辈缘；慎断子嗣，不作恐吓。',
    lookupLabel: '图鉴入口 · 对照十神食伤',
    lookupLines: aliasEntryLookupLines(
      '子孙星',
      '排盘以食伤等为对照；本条解边界，慎断子嗣',
    ),
    lookupPeer: '十神→子孙入口',
    likes: ['创造表达', '合食伤原局', '慎断子嗣'],
    dislikes: ['恐吓式无后', '道德绑架', '脱离十神'],
    strength: '创造、表达、晚辈议题提醒。',
    career: '利创意产出。',
    wealth: '技能变现。',
    love: '创造连接；慎断子女。',
    body: '思虑活跃；作息。',
    chartExtra: '入口词，慎断子嗣吉凶。',
    positive: '正面：能创造。失衡：恐吓绑架。',
    memory: '子孙星入口 = 食伤对照慎断。辅助，勿单独断。',
    coreKeyword: '子孙星 · 食伤入口',
    pillarMeaning: {
      year: '年柱议题见子孙对照：早年创造/晚辈氛围。',
      month: '月柱议题见子孙对照：事业创意窗口。',
      day: '日柱议题见子孙对照：本人表达创造感。',
      hour: '时柱议题见子孙对照：出口/晚辈议题慎断。',
    },
  }),
  'ss:胎神': rich({
    name: '胎神',
    whatIs:
      '胎神是什么：十二长生「胎」位——孕育、安胎方位说法入口。像种子在土里；宜护持，慎断生育吉凶。',
    lookupLabel: '日干对支取「胎」',
    lookupLines: changShengStageLookupLines('胎'),
    lookupPeer: '日干→胎',
    likes: ['护持与准备', '合养神看', '慎断生育'],
    dislikes: ['恐吓式胎产断语', '迷信取代医疗', '脱离原局'],
    strength: '孕育准备、潜藏生机。',
    career: '利孵化期项目；别过早曝光。',
    wealth: '种子资金宜护。',
    love: '慢养关系；慎断胎产。',
    body: '遵医嘱；作息托底。',
    chartExtra: '长生位入口；医疗优先于迷信。',
    positive: '正面：能孕育。失衡：恐吓迷信。',
    memory: '胎神 = 长生胎位：护持慎断。辅助，勿单独断。',
    coreKeyword: '胎神 · 孕育入口',
    pillarMeaning: {
      year: '年柱见胎：早年潜藏/孕育议题。',
      month: '月柱见胎：事业孵化期。',
      day: '日柱见胎：本人潜藏生机；护持。',
      hour: '时柱见胎：出口期宜慢养。',
    },
  }),
  'ss:养神': rich({
    name: '养神',
    whatIs:
      '养神是什么：十二长生「养」位——孕育准备、滋养气场。像育苗期；宜规律养护，不是必结果。',
    lookupLabel: '日干对支取「养」',
    lookupLines: changShengStageLookupLines('养'),
    lookupPeer: '日干→养',
    likes: ['规律养护', '合胎神看', '小步育苗'],
    dislikes: ['当作必成', '拔苗助长', '脱离原局'],
    strength: '滋养、准备、慢生长。',
    career: '利基础建设期。',
    wealth: '宜定投式积累。',
    love: '慢热滋养。',
    body: '作息饮食托底。',
    chartExtra: '长生养位；要耐心。',
    positive: '正面：能养。失衡：空等或拔苗。',
    memory: '养神 = 长生养位：育苗耐心。辅助，勿单独断。',
    coreKeyword: '养神 · 滋养准备',
    pillarMeaning: {
      year: '年柱见养：早年滋养底色。',
      month: '月柱见养：事业打基础窗口。',
      day: '日柱见养：本人需滋养节奏。',
      hour: '时柱见养：出口期宜慢养成果。',
    },
  }),
  'ss:长生': rich({
    name: '长生',
    whatIs:
      '长生是什么：十二长生「长生」位——起势与生机。像破土出芽；宜呵护起步，不是必大成。',
    lookupLabel: '日干对支取「长生」',
    lookupLines: changShengStageLookupLines('长生'),
    lookupPeer: '日干→长生',
    likes: ['呵护起步', '合帝旺对照', '小步验证'],
    dislikes: ['当作必成大事', '忽略养护', '脱离原局'],
    strength: '起势、生机、新开端。',
    career: '利新项目启动。',
    wealth: '宜种子轮小步。',
    love: '新缘慢养。',
    body: '生机期也勿透支。',
    chartExtra: '长生起势；要呵护。',
    positive: '正面：有生机。失衡：空喊起势。',
    memory: '长生 = 起势生机：呵护验证。辅助，勿单独断。',
    coreKeyword: '长生 · 起势生机',
    pillarMeaning: {
      year: '年柱见长生：早年起势氛围。',
      month: '月柱见长生：事业启动窗口。',
      day: '日柱见长生：本人生机感；呵护。',
      hour: '时柱见长生：出口期新芽成果。',
    },
  }),
  'ss:帝旺': rich({
    name: '帝旺',
    whatIs:
      '帝旺是什么：十二长生「帝旺」位——巅峰气场。像正午烈日；宜借势也防过曝，不是必永久巅峰。',
    lookupLabel: '日干对支取「帝旺」',
    lookupLines: changShengStageLookupLines('帝旺'),
    lookupPeer: '日干→帝旺',
    likes: ['借势交付', '合长生/墓库看', '防过曝'],
    dislikes: ['当作永巅峰', '透支硬撑', '脱离原局'],
    strength: '巅峰可见度、能量高。',
    career: '利关键发布；留接班节奏。',
    wealth: '高峰期落袋为安。',
    love: '高光也要平等。',
    body: '亢奋伤睡；降温。',
    chartExtra: '帝旺巅峰；防过刚过曝。',
    positive: '正面：能登顶。失衡：透支虚顶。',
    memory: '帝旺 = 巅峰气：借势防曝。辅助，勿单独断。',
    coreKeyword: '帝旺 · 巅峰气场',
    pillarMeaning: {
      year: '年柱见帝旺：早年高光/压力议题。',
      month: '月柱见帝旺：事业巅峰窗口。',
      day: '日柱见帝旺：本人巅峰感；防过曝。',
      hour: '时柱见帝旺：出口期高光宜收。',
    },
  }),
  'ss:墓库': rich({
    name: '墓库',
    whatIs:
      '墓库是什么：十二长生「墓」位——收藏、入库、沉淀。像收进匣子；要出入节奏，不是锁死。',
    lookupLabel: '日干对支取「墓」',
    lookupLines: changShengStageLookupLines('墓'),
    lookupPeer: '日干→墓库',
    likes: ['入库清淤', '合仓廪看', '定期出库'],
    dislikes: ['当作必困死', '只藏不流', '恐吓墓绝'],
    strength: '沉淀、收藏、成库。',
    career: '利归档标准化；要出库试用。',
    wealth: '资产入库；忌死守。',
    love: '情绪入库也要说。',
    body: '沉重感先动起来。',
    chartExtra: '墓库存取；要流通。',
    positive: '正面：能沉淀。失衡：锁死恐吓。',
    memory: '墓库 = 长生墓：收藏要流。辅助，勿单独断。',
    coreKeyword: '墓库 · 收藏沉淀',
    pillarMeaning: {
      year: '年柱见墓库：早年收藏/沉淀议题。',
      month: '月柱见墓库：事业入库窗口。',
      day: '日柱见墓库：本人沉淀感；要出库。',
      hour: '时柱见墓库：出口期宜归档也留门。',
    },
  }),
  'ss:旬空': rich({
    name: '旬空',
    whatIs:
      '旬空是什么：空亡的别称入口。日柱所在旬两支落空——力气虚着，宜借实处；不是一切落空。',
    lookupLabel: '日柱旬空（同空亡）',
    lookupLines: xunKongLookupLines(),
    lookupPeer: '日柱→旬空',
    likes: ['借实试点', '合空亡看', '小步核实'],
    dislikes: ['恐吓一切落空', '梭哈虚处', '脱离原局'],
    strength: '提醒虚位、促使借实。',
    career: '虚处试点；实处加码。',
    wealth: '大额核实再付。',
    love: '承诺先核实。',
    body: '空感时先睡够。',
    chartExtra: '与空亡同查；别称入口。',
    positive: '正面：促使借实。失衡：恐吓落空。',
    memory: '旬空 = 空亡别称：虚处借实。辅助，勿单独断。',
    coreKeyword: '旬空 · 虚位借实',
    pillarMeaning: {
      year: '年柱支逢旬空：早年根基力气偏虚，宜借实。',
      month: '月柱支逢旬空：事业当令处宜试点。',
      day: '日柱支逢旬空：自我场易发空感；先核实。',
      hour: '时柱支逢旬空：出口宜小步实事。',
    },
  }),
  'ss:天罗地网': rich({
    name: '天罗地网',
    whatIs:
      '天罗地网是什么：困局总称入口。火命戌亥为天罗、水土命辰巳为地网——像罩与网；宜绕行清淤，不是绝路。',
    lookupLabel: '年命纳音 × 戌亥/辰巳',
    lookupLines: tianLuoDiWangLookupLines(),
    lookupPeer: '年命→天罗地网',
    likes: ['绕行清淤', '合天罗/地网看', 'Plan B'],
    dislikes: ['恐吓式绝路', '硬闯', '无备份'],
    strength: '困局总提醒、促使换道。',
    career: '关键节点留退路。',
    wealth: '大额复核。',
    love: '窒息时开窗。',
    body: '压抑伤睡；活动。',
    chartExtra: '总称入口；非永久封死。',
    positive: '正面：促使绕行。失衡：恐吓硬闯。',
    memory: '天罗地网 = 困局总称：绕行清淤。辅助，勿单独断。',
    coreKeyword: '天罗地网 · 困局总览',
    pillarMeaning: {
      year: '年柱见天罗地网：早年困局议题。',
      month: '月柱见天罗地网：事业关口宜 Plan B。',
      day: '日柱见天罗地网：本人易感罩网；换道。',
      hour: '时柱见天罗地网：出口前复查退路。',
    },
  }),
};
