import type { CardKnowledge } from '../types.ts';

/** 大阿尔克那深度资料（除 major-five / deep-ten 已覆盖外） */
export const MAJOR_REST_KNOWLEDGE: CardKnowledge[] = [
  {
    id: 'the_magician',
    deckId: 'major-1',
    nameCn: '魔术师',
    nameEn: 'The Magician',
    arcana: 'major',
    number: 1,
    keywords: ["意志","创造","专注","资源整合","行动"],
    uprightKeywords: ["意志","专注","创造","资源齐备","显化"],
    reversedKeywords: ["才能未发","欺骗","分散","操控","自我怀疑"],
    oneSentence: "魔术师像站在祭坛前的施术者——桌上四元素齐备，头顶无限符号，一指天一指地。",
    uprightMeaning: "正位时你拥有把想法化为现实的工具与专注。关键是选一个方向，把能量集中在一点。",
    reversedMeaning: "逆位暗示才能未发挥、自我怀疑，或用巧言掩饰准备不足。警惕操控与被操控。",
    loveMeaning: "感情上，魔术师像主动表达、制造惊喜或「我能为这段关系做点什么」。真诚比套路重要。",
    workMeaning: "工作上，魔术师对应展示能力、提案、面试或项目启动。把资源摆到桌面上。",
    wealthMeaning: "财富议题里，魔术师像副业变现、谈判或把技能换成收入。能力已有，差在执行。",
    studyMeaning: "学业上，魔术师鼓励主动学习方法、请教导师。你比想象中更有掌控力。",
    selfMeaning: "自我层面，魔术师问你：你打算把意志投向哪里？",
    misreadings: ["误读为「一定成功」——资源齐备不等于已行动。","误读为「骗术」——正位是显化，逆位才警示操纵。"],
    visualOverview: "魔术师一手指天一手接地，桌上摆放权杖、圣杯、宝剑与星币，头顶无限符号。意志与四元素齐聚，等待专注施展。",
  },
  {
    id: 'the_empress',
    deckId: 'major-3',
    nameCn: '皇后',
    nameEn: 'The Empress',
    arcana: 'major',
    number: 3,
    keywords: ["丰饶","滋养","创造","感官","成长"],
    uprightKeywords: ["丰饶","滋养","创造","孕育","感官愉悦"],
    reversedKeywords: ["创造力受阻","过度依赖","忽视自我","停滞"],
    oneSentence: "皇后像坐在麦田中的丰饶之母——星冠、流水与成熟谷物环绕，万物正在生长。",
    uprightMeaning: "正位时适合培育：计划、关系、身体或作品。给予时间与照料，成果会自然生长。",
    reversedMeaning: "逆位暗示过度付出、创造力卡住或忽视自身需求。滋养他人前，先浇灌自己。",
    loveMeaning: "感情上，皇后代表温柔、承诺与感官亲密。适合深化关系，而非急于定义。",
    workMeaning: "工作上，皇后像培育团队、打磨产品或创意项目进入收获期。耐心是策略。",
    wealthMeaning: "财富议题里，皇后指向稳定积累、资产增值或「让钱生钱」的耐心布局。",
    studyMeaning: "学业上，皇后鼓励沉浸式学习、发挥创造力。成长急不得。",
    selfMeaning: "自我层面，皇后邀请你善待身体与欲望——丰盛包含对自己好。",
    misreadings: ["误读为「只有怀孕」——是滋养与创造主题。","误读为「享乐无度」——正位是健康丰盛。"],
    visualOverview: "皇后安坐麦田软垫，星冠在顶，身后森林流水潺潺。像丰饶之母，万物在照料中生长。",
  },
  {
    id: 'the_emperor',
    deckId: 'major-4',
    nameCn: '皇帝',
    nameEn: 'The Emperor',
    arcana: 'major',
    number: 4,
    keywords: ["结构","权威","秩序","决断","边界"],
    uprightKeywords: ["结构","权威","秩序","决断","稳定框架"],
    reversedKeywords: ["专制","僵化","失控","滥用权力","缺乏自律"],
    oneSentence: "皇帝像坐在石座上的统治者——手持权杖，远山在后，象征以结构掌控局面。",
    uprightMeaning: "正位时需要建立规则、边界与计划。理性决断比情绪反应更能稳住局面。",
    reversedMeaning: "逆位警示过度控制或反而失控。僵化规则会反噬，也需审视权力如何使用。",
    loveMeaning: "感情上，皇帝像需要承诺、边界与安全感。可能偏理性，记得留出柔软空间。",
    workMeaning: "工作上，皇帝对应升职、管理岗、制定制度或拍板决策。领导力被召唤。",
    wealthMeaning: "财富议题里，皇帝像预算、资产配置、长期规划。守纪律比追热点重要。",
    studyMeaning: "学业上，皇帝鼓励制定计划、自律复习。结构感帮你扛过倦怠期。",
    selfMeaning: "自我层面，皇帝问你：你的人生规则，是保护你还是囚禁你？",
    misreadings: ["误读为「只有男性」——是结构能量，不限性别。","误读为「冷酷」——稳定也可以有温度。"],
    visualOverview: "皇帝端坐石制王座，手持权杖，身披红袍，远山矗立身后。秩序、边界与理性决断的象征。",
  },
  {
    id: 'the_hierophant',
    deckId: 'major-5',
    nameCn: '教皇',
    nameEn: 'The Hierophant',
    arcana: 'major',
    number: 5,
    keywords: ["传统","信念","传承","学习","体系"],
    uprightKeywords: ["传统","信念","导师","制度","传承"],
    reversedKeywords: ["打破陈规","盲从","教条","信仰危机"],
    oneSentence: "教皇像坐在神殿中的导师——交叉钥匙在前，两名侍从聆听，象征传统与传承。",
    uprightMeaning: "正位时可借力制度、导师、信念体系。学习已有智慧，再内化为自己的理解。",
    reversedMeaning: "逆位鼓励独立思考，质疑不再服务的教条。不必盲从，但要清楚自己相信什么。",
    loveMeaning: "感情上，教皇可能指向婚姻、家庭认可或价值观是否被双方家族接受。",
    workMeaning: "工作上，教皇像培训、考证、入行规范或融入组织文化。找导师少走弯路。",
    wealthMeaning: "财富议题里，教皇提醒遵守规则、合规经营。传统路径稳健但非唯一。",
    studyMeaning: "学业上，教皇极利备考、拜师、系统学习。站在巨人肩上。",
    selfMeaning: "自我层面，教皇问你：哪些信念来自他人，哪些真正属于你？",
    misreadings: ["误读为「宗教牌」——指传承与信念体系。","误读为「必须听话」——逆位鼓励清醒选择。"],
    visualOverview: "教皇端坐神殿，手持三重十字杖，脚前交叉钥匙，两名侍从聆听。传统、传承与信念体系的象征。",
  },
  {
    id: 'the_chariot',
    deckId: 'major-7',
    nameCn: '战车',
    nameEn: 'The Chariot',
    arcana: 'major',
    number: 7,
    keywords: ["胜利","意志","推进","掌控","突破"],
    uprightKeywords: ["胜利","意志","推进","自律","突破障碍"],
    reversedKeywords: ["失控","方向迷失","内在冲突","蛮力"],
    oneSentence: "战车像驭者驾驶双狮拉的车——黑白狮身象征内在冲突，华盖下意志向前。",
    uprightMeaning: "正位时以专注意志克服障碍，自律与方向一致时能赢得阶段性胜利。",
    reversedMeaning: "逆位暗示方向迷失或内在拉扯：一黑一白，车再快也到不了。",
    loveMeaning: "感情上，战车像主动推进关系、克服异地或外在阻力。问：双方是否同向？",
    workMeaning: "工作上，战车对应竞标成功、项目冲刺、升职竞争。全力推进，但别失控。",
    wealthMeaning: "财富议题里，战车像冲刺业绩、快速成交。胜利在望，注意节奏与风险。",
    studyMeaning: "学业上，战车鼓励考前冲刺、咬牙坚持。短期爆发需配长期节奏。",
    selfMeaning: "自我层面，战车问你：驱动你向前的，是真心还是恐惧？",
    misreadings: ["误读为「一定赢」——是意志主题，结果看方向。","误读为「不需调和」——双狮必须先统一。"],
    visualOverview: "驭者站在战车中，黑白狮身拉车向前，身后城邦远去。意志驱动突破，但内在须先调和。",
  },
  {
    id: 'strength',
    deckId: 'major-8',
    nameCn: '力量',
    nameEn: 'Strength',
    arcana: 'major',
    number: 8,
    keywords: ["勇气","耐心","温柔的力量","驯服","自信"],
    uprightKeywords: ["勇气","耐心","温柔","自信","驯服野性"],
    reversedKeywords: ["自我怀疑","情绪失控","软弱感","用蛮力"],
    oneSentence: "力量像女子温柔合上狮口——不是压制，而是以耐心与同理驯服内在野性。",
    uprightMeaning: "正位时真正的力量来自温柔与耐心。以自信面对挑战，而非暴力压制。",
    reversedMeaning: "逆位暗示自我怀疑或情绪失控。重建力量从接纳脆弱开始。",
    loveMeaning: "感情上，力量像以耐心化解冲突、温柔表达需求。硬碰硬只会让狮醒来。",
    workMeaning: "工作上，力量对应高压下的稳定、领导者的情商、或长期坚持。",
    wealthMeaning: "财富议题里，力量像长期持有、克制冲动消费。慢即是快。",
    studyMeaning: "学业上，力量鼓励克服畏难，用耐心啃硬骨头。自信来自积累。",
    selfMeaning: "自我层面，力量问你：你如何与内心的狮子相处？",
    misreadings: ["误读为「体力」——是心灵力量。","误读为「不能愤怒」——是驯服而非消灭。"],
    visualOverview: "女子头戴花环，轻合狮口，头顶无限符号。温柔与耐心驯服野性，才是真力量。",
  },
  {
    id: 'the_hermit',
    deckId: 'major-9',
    nameCn: '隐者',
    nameEn: 'The Hermit',
    arcana: 'major',
    number: 9,
    keywords: ["内省","独处","智慧","指引","慢下来"],
    uprightKeywords: ["内省","独处","智慧","慢下来","内在光"],
    reversedKeywords: ["孤立","逃避","拒绝帮助","过度封闭"],
    oneSentence: "隐者像站在山巅举灯的老人——灯笼只照亮下一步，手杖伴他走过内在长路。",
    uprightMeaning: "正位邀请暂时退出喧嚣，在独处中听见答案。微光足够指引下一步。",
    reversedMeaning: "逆位警示过度孤立或拒绝他人帮助。独处有益，别把自己封死。",
    loveMeaning: "感情上，隐者像需要空间、暂停约会或「我想清楚再联系」。尊重节奏。",
    workMeaning: "工作上，隐者对应深度思考、转行酝酿、或远离办公室政治。",
    wealthMeaning: "财富议题里，隐者提醒慢决策、研究清楚再投。别跟风。",
    studyMeaning: "学业上，隐者极利复习、写论文、独自钻研。质量胜过速度。",
    selfMeaning: "自我层面，隐者问你：你害怕独处，还是害怕听见自己？",
    misreadings: ["误读为「孤独终老」——是阶段性内省。","误读为「必须离职隐居」——可以是每晚半小时安静。"],
    visualOverview: "灰袍老者立于山巅，手提灯笼，杖伴身侧。灯光只照下一步，内省之路漫长而清醒。",
  },
  {
    id: 'wheel_of_fortune',
    deckId: 'major-10',
    nameCn: '命运之轮',
    nameEn: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    keywords: ["转变","周期","机遇","命运","起伏"],
    uprightKeywords: ["转折","周期","机遇","顺势而为","命运转动"],
    reversedKeywords: ["阻滞","坏运气","抗拒变化","低谷"],
    oneSentence: "命运之轮像巨大的轮盘在转动——sphinx 在上，蛇下降，阿努比斯上升，起落是常态。",
    uprightMeaning: "正位标志转折来临。接受变化、顺势而为，好运正在转动到你这边。",
    reversedMeaning: "逆位暗示阻滞或坏运气。变化难免，低谷里积蓄力量，等待下一轮。",
    loveMeaning: "感情上，命运之轮像关系进入新阶段、偶遇或「没想到会在一起」。接受流动。",
    workMeaning: "工作上，命运之轮对应行业变动、意外机会或项目转机。保持灵活。",
    wealthMeaning: "财富议题里，命运之轮像市场周期、意外之财或亏损。别在顶峰忘形、谷底绝望。",
    studyMeaning: "学业上，命运之轮提醒考运起伏。准备充分，把运气留给有准备的人。",
    selfMeaning: "自我层面，命运之轮问你：你能否在起落中仍保持中心？",
    misreadings: ["误读为「全靠命运」——是周期，仍要你站位。","误读为「永远好运」——轮盘必转。"],
    visualOverview: "巨大轮盘中央转动，sphinx 端坐上方，蛇与阿努比斯分列两侧。命运起落，关键是你在哪一层。",
  },
  {
    id: 'justice',
    deckId: 'major-11',
    nameCn: '正义',
    nameEn: 'Justice',
    arcana: 'major',
    number: 11,
    keywords: ["公平","真相","因果","权衡","诚实"],
    uprightKeywords: ["公平","真相","因果","权衡","诚实"],
    reversedKeywords: ["不公","偏见","逃避责任","失衡"],
    oneSentence: "正义像端坐的天平与剑——一手权衡，一手真相，因果终将显形。",
    uprightMeaning: "正位强调诚实面对自己与他人。决定将得到公正结果，事实比感受更有重量。",
    reversedMeaning: "逆位警示偏见、不公或逃避责任。寻求澄清，别假装看不见。",
    loveMeaning: "感情上，正义像需要坦诚、谈清楚权责或「我们公平吗」。",
    workMeaning: "工作上，正义对应合同、仲裁、绩效评估。按规则办事，证据说话。",
    wealthMeaning: "财富议题里，正义提醒报税、合规、账目清楚。短期取巧长期反噬。",
    studyMeaning: "学业上，正义像考试公平、评分透明。付出与结果应匹配。",
    selfMeaning: "自我层面，正义问你：你对自己诚实吗？",
    misreadings: ["误读为「法律牌」——是因果与公平原则。","误读为「立刻报应」——是趋势，非即时。"],
    visualOverview: "正义女神端坐，一手天平一手宝剑，红袍庄严。公平、真相与因果在此权衡。",
  },
  {
    id: 'the_hanged_man',
    deckId: 'major-12',
    nameCn: '倒吊人',
    nameEn: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    keywords: ["暂停","换位思考","牺牲","等待","新视角"],
    uprightKeywords: ["暂停","换位思考","放手","等待","新视角"],
    reversedKeywords: ["无谓拖延","抗拒牺牲","停滞","受害者心态"],
    oneSentence: "倒吊人像头下脚上挂在树上的人——光环在头后，像主动暂停以换取新视角。",
    uprightMeaning: "正位时放手与等待比硬推更有效。牺牲眼前利益，可能换来更深领悟。",
    reversedMeaning: "逆位暗示以等待为借口的不作为，或抗拒必要调整。该动时需动。",
    loveMeaning: "感情上，倒吊人像冷战、被动等待或「我退一步看看」。暂停要有期限。",
    workMeaning: "工作上，倒吊人对应项目搁置、换角度复盘或短期牺牲换长期。",
    wealthMeaning: "财富议题里，倒吊人像资金冻结、短期亏损换布局。别 panic sell。",
    studyMeaning: "学业上，倒吊人鼓励换学习方法、休息充电。有时停一下反而通。",
    selfMeaning: "自我层面，倒吊人问你：你执着不放的，值不值得？",
    misreadings: ["误读为「惩罚」——多是自愿暂停。","误读为「永远卡住」——是阶段，不是终局。"],
    visualOverview: "男子倒吊生命之树，一腿交叉，头后光环平静。暂停不是失败，是为换取新视角。",
  },
  {
    id: 'death',
    deckId: 'major-13',
    nameCn: '死神',
    nameEn: 'Death',
    arcana: 'major',
    number: 13,
    keywords: ["结束","转化","重生","放下","新章"],
    uprightKeywords: ["结束","转化","重生","放下","蜕变"],
    reversedKeywords: ["抗拒改变","拖延结束","恐惧转化","半死不活"],
    oneSentence: "死神像白马骑士举着白旗——旧章落幕，不是毁灭，是为新生腾出空间。",
    uprightMeaning: "正位象征必要的结束与转化。放下不再服务的，才能迎接新的可能。",
    reversedMeaning: "逆位暗示抗拒改变、紧抓过去。越拖越痛，结束可以是干净的。",
    loveMeaning: "感情上，死神像关系形态必须改变：分手、结婚、或旧模式死亡。",
    workMeaning: "工作上，死神对应离职、转行、项目终结。结束是下一程的起点。",
    wealthMeaning: "财富议题里，死神像砍掉亏损、结束旧有收入模式。止损也是智慧。",
    studyMeaning: "学业上，死神像毕业、换专业、放弃不适合的路径。",
    selfMeaning: "自我层面，死神问你：你准备好让哪个旧我死去？",
    misreadings: ["误读为「死亡」——是象征性结束。","误读为「只有坏」——转化带来新生。"],
    visualOverview: "骷髅骑士骑白马，白旗飘扬，国王、妇孺跪迎。旧章落幕，转化干净而必然。",
  },
  {
    id: 'temperance',
    deckId: 'major-14',
    nameCn: '节制',
    nameEn: 'Temperance',
    arcana: 'major',
    number: 14,
    keywords: ["平衡","调和","耐心","中庸","疗愈"],
    uprightKeywords: ["平衡","调和","耐心","中庸","流动"],
    reversedKeywords: ["失衡","急躁","极端","过度"],
    oneSentence: "节制像天使在两岸间倒水——一脚踩水一脚踩岸，双杯流动，慢慢调成和谐。",
    uprightMeaning: "正位倡导耐心调和，在极端间找第三条路。循序渐进达成和谐。",
    reversedMeaning: "逆位表示失衡与急躁。过度或不足，需重新校准比例。",
    loveMeaning: "感情上，节制像慢慢磨合、不急于定义，把不同节奏调成共振。",
    workMeaning: "工作上，节制对应跨部门协作、长期项目、稳中求进。",
    wealthMeaning: "财富议题里，节制像资产配置、定投、收支平衡。慢调比梭哈稳。",
    studyMeaning: "学业上，节制鼓励劳逸结合、可持续节奏。马拉松，不是百米。",
    selfMeaning: "自我层面，节制问你：你的生活哪边太多、哪边太少？",
    misreadings: ["误读为「无聊」——是深度和谐。","误读为「不能激情」——是调配，不是消灭。"],
    visualOverview: "天使一脚踩水一脚踩岸，双杯间水流循环，远方阳光小径。耐心调和，极端之间仍有路。",
  },
  {
    id: 'the_devil',
    deckId: 'major-15',
    nameCn: '恶魔',
    nameEn: 'The Devil',
    arcana: 'major',
    number: 15,
    keywords: ["束缚","欲望","执念","成瘾","阴影"],
    uprightKeywords: ["束缚","欲望","执念","成瘾","觉察"],
    reversedKeywords: ["挣脱","觉醒","松绑","面对阴影"],
    oneSentence: "恶魔像笼中二人被松散锁链拴住——锁链松垮，觉察什么在控制你，才有解脱。",
    uprightMeaning: "正位揭示欲望、执念或无形束缚。习惯、恐惧、依赖可能比你以为的更紧。",
    reversedMeaning: "逆位象征打破枷锁、从有毒模式抽离。你有松绑的空间。",
    loveMeaning: "感情上，恶魔像占有欲、三角关系、或「明知不好却离不开」。",
    workMeaning: "工作上，恶魔对应过劳文化、金手铐、或只为钱忍受厌恶的工作。",
    wealthMeaning: "财富议题里，恶魔像赌博、消费成瘾、或债务循环。觉察链条。",
    studyMeaning: "学业上，恶魔像拖延成瘾、刷手机逃避。看见模式才能改。",
    selfMeaning: "自我层面，恶魔问你：什么欲望在替你做决定？",
    misreadings: ["误读为「邪恶」——是心理束缚。","误读为「无法摆脱」——锁链是松的。"],
    visualOverview: "恶魔坐石座，倒火炬在握，二人被松散锁链拴住。束缚看似坚固，实则仍有松绑空间。",
  },
  {
    id: 'the_sun',
    deckId: 'major-19',
    nameCn: '太阳',
    nameEn: 'The Sun',
    arcana: 'major',
    number: 19,
    keywords: ["喜悦","成功","清晰","生命力","自信"],
    uprightKeywords: ["喜悦","成功","清晰","生命力","自信"],
    reversedKeywords: ["快乐受阻","过度乐观","短暂阴霾","自信不足"],
    oneSentence: "太阳像孩童骑马穿过向日葵田——巨日当空，一切明朗，生命力绽放。",
    uprightMeaning: "正位是喜悦、成功与清晰。阴霾暂退，值得庆祝，也保持开放。",
    reversedMeaning: "逆位表示快乐暂时受阻或过度乐观。小小阴影遮不住本质的光。",
    loveMeaning: "感情上，太阳像关系明朗、公开恋情、或单纯快乐的相处。",
    workMeaning: "工作上，太阳对应项目成功、被认可、面试顺利。成绩值得看见。",
    wealthMeaning: "财富议题里，太阳像收入改善、投资盈利。享受成果，别得意忘形。",
    studyMeaning: "学业上，太阳像考试顺利、成绩公布好消息。自信来自真实努力。",
    selfMeaning: "自我层面，太阳邀请你像孩子一样相信生命可以喜悦。",
    misreadings: ["误读为「没有阴影」——逆位仍有小波折。","误读为「不劳而获」——喜悦常是努力后的光。"],
    visualOverview: "巨日当空，孩童骑马持旗穿过向日葵，矮墙在后。喜悦、清晰与生命力一并绽放。",
  },
  {
    id: 'judgement',
    deckId: 'major-20',
    nameCn: '审判',
    nameEn: 'Judgement',
    arcana: 'major',
    number: 20,
    keywords: ["觉醒","召唤","复盘","重生","抉择"],
    uprightKeywords: ["觉醒","召唤","复盘","重生","回应内心"],
    reversedKeywords: ["自我批判","逃避反省","迟迟不应","苛责"],
    oneSentence: "审判像天使吹响号角——人们从棺中起身，回应内心召唤，做出符合真我的抉择。",
    uprightMeaning: "正位呼唤觉醒与复盘。回顾过往，听从召唤，做出清醒决定。",
    reversedMeaning: "逆位暗示自我批判过重或逃避反省。诚实但不残忍地面对自己。",
    loveMeaning: "感情上，审判像关系复盘、复合与否、或「我们是否该进入下一阶段」。",
    workMeaning: "工作上，审判对应职业召唤、是否回归本行、重大抉择节点。",
    wealthMeaning: "财富议题里，审判像财务清算、遗产、或「这笔钱花得值不值」的反思。",
    studyMeaning: "学业上，审判像择校、考研结果、或是否继续这条学术路。",
    selfMeaning: "自我层面，审判问你：你听见内心的召唤了吗？",
    misreadings: ["误读为「宗教审判」——是自我觉醒。","误读为「只有对错」——是召唤与选择。"],
    visualOverview: "天使云端吹号，人们从棺中起身仰望，远方雪山。觉醒的召唤响起，旧我复活为新抉择。",
  },
  {
    id: 'the_world',
    deckId: 'major-21',
    nameCn: '世界',
    nameEn: 'The World',
    arcana: 'major',
    number: 21,
    keywords: ["完成","圆满","整合","成就","新周期"],
    uprightKeywords: ["完成","圆满","整合","成就","闭环"],
    reversedKeywords: ["未完成","差一步","延迟圆满","不敢收尾"],
    oneSentence: "世界像舞者在一个大圆环中——四角落有象征，一周期圆满完成，新的即将开始。",
    uprightMeaning: "正位标志重要旅程的完成与整合。可以庆祝成就，也为下一周期做准备。",
    reversedMeaning: "逆位表示临门一脚差一步，或不敢宣布完成。再坚持片刻，圆满触手可及。",
    loveMeaning: "感情上，世界像关系进入稳定阶段、结婚、或「我们一起走到了这里」。",
    workMeaning: "工作上，世界对应项目收官、毕业、升职达成。认可这段路。",
    wealthMeaning: "财富议题里，世界像目标达成、财务自由里程碑。整合成果，规划下一程。",
    studyMeaning: "学业上，世界像毕业、考证通过、学业阶段圆满。",
    selfMeaning: "自我层面，世界问你：你准备好承认自己已经走了多远吗？",
    misreadings: ["误读为「终点」——完成一个圆，开启下一个。","误读为「完美无缺」——是整合，不是无瑕。"],
    visualOverview: "舞者在花环中起舞，四角有天使、鹰、牛、狮。一周期圆满完成，新的循环即将展开。",
  },
];
