/**
 * 塔罗轻练习题库：大阿卡纳意象复习（非占卜鉴定）
 */
import type { LightGuessCard } from '../lab/light-guess.ts';

export const TAROT_GUESS_CARDS: LightGuessCard[] = [
  {
    id: 'tr-fool',
    name: '愚者',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「站在悬崖边要出发」的牌',
    clues: [
      '新开始、冒险、直觉先行',
      '行李很少，信任未知',
      '功课：勇气出发，但不是盲目乱冲',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '愚者' },
      { id: 'b', label: '战车' },
      { id: 'c', label: '隐者' },
    ],
    answerId: 'a',
    explainCorrect: '对。愚者是旅程的起点：好奇与跃入。',
    explainWrong: '战车偏意志推进，隐者偏内省退场；悬崖边出发是愚者。',
  },
  {
    id: 'tr-tower',
    name: '塔',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「旧结构突然崩」的牌',
    clues: [
      '突发变故、假稳定被拆穿',
      '痛，但清出重建空间',
      '不是纯倒霉，是醒觉的雷击',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '月亮' },
      { id: 'b', label: '塔' },
      { id: 'c', label: '节制' },
    ],
    answerId: 'b',
    explainCorrect: '对。塔是突变与旧框架崩塌。',
    explainWrong: '月亮偏迷雾幻象，节制偏调和；雷击崩塌是塔。',
  },
  {
    id: 'tr-star',
    name: '星星',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「黑暗后还有微光」的牌',
    clues: [
      '希望、疗愈、灵感',
      '常在冲击之后出现',
      '提醒：保持信念，小光也够引路',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '太阳' },
      { id: 'b', label: '世界' },
      { id: 'c', label: '星星' },
    ],
    answerId: 'c',
    explainCorrect: '对。星星是希望与疗愈的微光。',
    explainWrong: '太阳偏全然明亮成功，世界偏周期圆满；暗后微光是星星。',
  },
  {
    id: 'tr-death',
    name: '死神',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「旧章必须合上」的牌',
    clues: [
      '结束不是毁灭，是腾位置给新生',
      '抗拒改变会拖得更痛',
      '牌面常被误读成字面死亡',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '死神' },
      { id: 'b', label: '倒吊人' },
      { id: 'c', label: '恶魔' },
    ],
    answerId: 'a',
    explainCorrect: '对。死神主结束与蜕变重生。',
    explainWrong: '倒吊人偏暂停换位，恶魔偏束缚欲望；合上旧章是死神。',
  },
  {
    id: 'tr-lovers',
    name: '恋人',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「价值要对齐」的牌',
    clues: [
      '选择、联结、心与心的契合',
      '不只恋爱，也谈重大取舍',
      '功课：诚实面对分歧',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '教皇' },
      { id: 'b', label: '恋人' },
      { id: 'c', label: '正义' },
    ],
    answerId: 'b',
    explainCorrect: '对。恋人关乎价值一致的选择与联结。',
    explainWrong: '教皇偏传统指引，正义偏因果公平；心与选择对齐是恋人。',
  },
  {
    id: 'tr-hermit',
    name: '隐者',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「先退出喧嚣」的牌',
    clues: [
      '内省、独处、提灯找答案',
      '不是永久Isolated，是暂时退场',
      '功课：独处有益，别封闭成拒绝帮助',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '隐者' },
      { id: 'b', label: '魔术师' },
      { id: 'c', label: '皇帝' },
    ],
    answerId: 'a',
    explainCorrect: '对。隐者邀请内省与独自寻路。',
    explainWrong: '魔术师偏把想法落地，皇帝偏秩序权威；提灯独处是隐者。',
  },
  {
    id: 'tr-magician',
    name: '魔术师',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「桌上四样工具齐了」的牌',
    clues: [
      '意志、技巧、资源在手',
      '适合把想法做成现实',
      '功课：专注与诚信，别用巧言空转',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '女祭司' },
      { id: 'b', label: '命运之轮' },
      { id: 'c', label: '魔术师' },
    ],
    answerId: 'c',
    explainCorrect: '对。魔术师是意志与资源对齐、开始创造。',
    explainWrong: '女祭司偏内在直觉，命运之轮偏周期转折；动手创造是魔术师。',
  },
  {
    id: 'tr-strength',
    name: '力量',
    kind: '大阿卡纳',
    sealedLabel: '今日盲盒 · 一张「温柔驯服野兽」的牌',
    clues: [
      '勇气来自耐心与同理，不是蛮力',
      '内在野性需要被引导，不是被抹杀',
      '功课：从接纳脆弱建立真力量',
    ],
    question: '它更像哪张牌？',
    options: [
      { id: 'a', label: '战车' },
      { id: 'b', label: '力量' },
      { id: 'c', label: '审判' },
    ],
    answerId: 'b',
    explainCorrect: '对。力量是柔而有力的驯服与勇气。',
    explainWrong: '战车偏外在意志推进，审判偏觉醒召唤；温柔驯服是力量。',
  },
];
