/**
 * 紫微轻练习题库：星曜 / 宫位意象复习（非排盘鉴定）
 */
import type { LightGuessCard } from '../lab/light-guess.ts';

export const ZIWEI_GUESS_CARDS: LightGuessCard[] = [
  {
    id: 'zw-ziwei',
    name: '紫微',
    kind: '主星',
    sealedLabel: '今日盲盒 · 一颗「帝王气场」的主星',
    clues: [
      '像舞台中央的主角，天然被看见',
      '要面子、要秩序，也要人托住场面',
      '落命宫时，人设常偏「主导 / 被期待」',
    ],
    question: '它更像哪颗主星？',
    options: [
      { id: 'a', label: '紫微' },
      { id: 'b', label: '破军' },
      { id: 'c', label: '天机' },
    ],
    answerId: 'a',
    explainCorrect: '对。紫微是帝星意象：中心、体面、要人配合的舞台感。',
    explainWrong: '破军偏冲开重组，天机偏谋划变通；帝座中心感才是紫微。',
  },
  {
    id: 'zw-qisha',
    name: '七杀',
    kind: '主星',
    sealedLabel: '今日盲盒 · 一颗「锋利开创」的主星',
    clues: [
      '行动快、敢冲，气场偏刀锋',
      '适合破局，不适合慢慢熬',
      '要学的是收放，不是磨平锋芒',
    ],
    question: '它更像哪颗主星？',
    options: [
      { id: 'a', label: '天同' },
      { id: 'b', label: '七杀' },
      { id: 'c', label: '天梁' },
    ],
    answerId: 'b',
    explainCorrect: '对。七杀是开创与压力并进的刀锋星。',
    explainWrong: '天同偏安适，天梁偏荫护规矩；锋利开创是七杀。',
  },
  {
    id: 'zw-tianji',
    name: '天机',
    kind: '主星',
    sealedLabel: '今日盲盒 · 一颗「脑子转不停」的主星',
    clues: [
      '善变通、善谋划，点子多',
      '容易想太多、方案换太勤',
      '落宫处像「策略参谋」而不是硬刚主将',
    ],
    question: '它更像哪颗主星？',
    options: [
      { id: 'a', label: '武曲' },
      { id: 'b', label: '贪狼' },
      { id: 'c', label: '天机' },
    ],
    answerId: 'c',
    explainCorrect: '对。天机主智变与谋划，是盘上的策略引擎。',
    explainWrong: '武曲偏财事刚决，贪狼偏欲望与交际；多谋善变是天机。',
  },
  {
    id: 'zw-taiyin',
    name: '太阴',
    kind: '主星',
    sealedLabel: '今日盲盒 · 一颗「夜里才醒」的主星',
    clues: [
      '细腻、内收，感受力强',
      '场域偏私密、照护、审美',
      '强光场合反而容易耗',
    ],
    question: '它更像哪颗主星？',
    options: [
      { id: 'a', label: '太阳' },
      { id: 'b', label: '太阴' },
      { id: 'c', label: '廉贞' },
    ],
    answerId: 'b',
    explainCorrect: '对。太阴是月性：内收、滋养、夜里发光。',
    explainWrong: '太阳偏外放照人，廉贞偏二次曲线与纠结；夜里细腻是太阴。',
  },
  {
    id: 'zw-fuqi',
    name: '夫妻宫',
    kind: '十二宫',
    sealedLabel: '今日盲盒 · 一宫「亲密关系议题」',
    clues: [
      '看伴侣、合作亲密、一对一张力',
      '不是只谈结婚，也谈深度绑定',
      '读法：先主星气质，再叠四化与对宫',
    ],
    question: '它对应十二宫里的哪一宫？',
    options: [
      { id: 'a', label: '兄弟宫' },
      { id: 'b', label: '夫妻宫' },
      { id: 'c', label: '仆役宫' },
    ],
    answerId: 'b',
    explainCorrect: '对。夫妻宫主一对一亲密与深度绑定议题。',
    explainWrong: '兄弟偏平级伙伴，仆役偏部属人际；一对一亲密是夫妻宫。',
  },
  {
    id: 'zw-caibo',
    name: '财帛宫',
    kind: '十二宫',
    sealedLabel: '今日盲盒 · 一宫「钱与资源怎么来」',
    clues: [
      '看赚钱方式、现金流、资源胃口',
      '与官禄对照：做事 vs 收成',
      '落星决定你更像「稳收」还是「博窗口」',
    ],
    question: '它对应十二宫里的哪一宫？',
    options: [
      { id: 'a', label: '财帛宫' },
      { id: 'b', label: '田宅宫' },
      { id: 'c', label: '疾厄宫' },
    ],
    answerId: 'a',
    explainCorrect: '对。财帛宫看钱与资源如何进出。',
    explainWrong: '田宅偏不动产安顿，疾厄偏身心负荷；现金流议题在财帛。',
  },
  {
    id: 'zw-huaji',
    name: '化忌',
    kind: '四化',
    sealedLabel: '今日盲盒 · 一层「卡点提醒」的催化',
    clues: [
      '不是判死刑，是哪里易卡住、易执念',
      '落哪颗星/哪一宫，哪里议题更尖',
      '用法：把卡点写成可执行边界，而不是吓自己',
    ],
    question: '这层四化更像？',
    options: [
      { id: 'a', label: '化禄（资源满足）' },
      { id: 'b', label: '化权（掌控加力）' },
      { id: 'c', label: '化忌（卡点与执念）' },
    ],
    answerId: 'c',
    explainCorrect: '对。化忌是卡点/执念催化，提醒收束而非吓阻。',
    explainWrong: '化禄偏满足资源，化权偏掌控加力；卡点感是化忌。',
  },
  {
    id: 'zw-tanlang',
    name: '贪狼',
    kind: '主星',
    sealedLabel: '今日盲盒 · 一颗「欲望与交际」的主星',
    clues: [
      '想要得多：人、趣、机会、感官',
      '社交与魅力场常见',
      '功课是选，不是戒绝一切欲望',
    ],
    question: '它更像哪颗主星？',
    options: [
      { id: 'a', label: '天相' },
      { id: 'b', label: '贪狼' },
      { id: 'c', label: '天府' },
    ],
    answerId: 'b',
    explainCorrect: '对。贪狼主欲望、交际与多通道胃口。',
    explainWrong: '天相偏辅佐印信，天府偏库藏稳场；多欲交际是贪狼。',
  },
];
